[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/success"
  to = "/?s=success"
  status = 200

[[redirects]]
  from = "/cancel"
  to = "/?s=cancel"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
