[build]
  publish = "."

[[redirects]]
  from = "/success"
  to = "/?screen=success"
  status = 200

[[redirects]]
  from = "/cancel"
  to = "/?screen=cancel"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
